  { Begining of Core Object Injections }
  coAccount     {Account},
  coApp         {Applications},
  coCMS         {Content Management System},
  coPostInfo    {Post Info},
  coRSS         {RSS},
  coCalendar    {Calendar},
  coSearch      {Search System},
  coProviders   {Search Providers},
  coSessions    {Search Sessions},
  coLogin       {HTTP based authentication},
  coSyndication {RSS Publication},
  coQuill       {Blogging},
  coVendor      {Vendors},
  coSpectrum    {Spectrum},
  coSocial      {Social Networking},
  coAvatar      {Avatar Images},
  coVDM         {Virtual Desktop Manager},
  coPayments    {Credit Card Payment Methods},
  coPurchases   {Purchase Items},
  coCollages    {Collages}

  { End of Core Object Injections }
