var
  iLcv                  : LongInt;
  iLength               : LongInt;
  iRetries              : LongInt;
  sDataLengthStr        : Core.Strings.VarString;
  sTable                : Core.Strings.VarString;
  sFields               : Core.Strings.VarString;
  sCriteria             : Core.Strings.VarString;
  sOrderBy              : Core.Strings.VarString;
  sCommand              : Core.Strings.VarString;
  sLimit                : Core.Strings.VarString;

  Parameters            : Core.Database.Types.CommandParameters;
  TableP                : Core.Database.Types.PTable;


