Core.Database.AddCommand(iCount,DB.TableP,useForInsert,Integer(DB.IDs.DomainID),poNone,oNone,DomainID,Commands);
Core.Database.AddCommand(iCount,DB.TableP,useForInsert,Integer(DB.IDs.NetworkID),poNone,oNone,Item.NetworkID,Commands);
Core.Database.AddCommand(iCount,DB.TableP,useForInsert,Integer(DB.IDs.QueryID),poNone,oNone,Item.QueryID,Commands);
Core.Database.AddCommand(iCount,DB.TableP,useForInsert,Integer(DB.IDs.ResponseID),poNone,oNone,Item.ResponseID,Commands);
Core.Database.AddCommand(iCount,DB.TableP,useForInsert,Integer(DB.IDs.Opened),poNone,oNone,Item.Opened,Commands);
Core.Database.AddCommand(iCount,DB.TableP,useForInsert,Integer(DB.IDs.Closed),poNone,oNone,Item.Closed,Commands);
Core.Database.AddCommand(iCount,DB.TableP,useForInsert,Integer(DB.IDs.Expires),poNone,oNone,Item.Expires,Commands);
Core.Database.AddCommand(iCount,DB.TableP,useForInsert,Integer(DB.IDs.Flags),poNone,oNone,Item.Flags,Commands);
Core.Database.AddCommand(iCount,DB.TableP,useForInsert,Integer(DB.IDs.Query),poNone,oNone,Item.Query,Commands);
Core.Database.AddCommand(iCount,DB.TableP,useForInsert,Integer(DB.IDs.Response),poNone,oNone,Item.Response,Commands);

