Core.Database.AddCommand(iCount, DB.TableP, useForFields, DB.IDs.ID,poNone,oNone,Commands);
Core.Database.AddCommand(iCount, DB.TableP, useForFields, DB.IDs.Number,poNone,oNone,Commands);
Core.Database.AddCommand(iCount, DB.TableP, useForFields, DB.IDs.ExpMonth,poNone,oNone,Commands);
Core.Database.AddCommand(iCount, DB.TableP, useForFields, DB.IDs.ExpYear,poNone,oNone,Commands);
Core.Database.AddCommand(iCount, DB.TableP, useForFields, DB.IDs.Code,poNone,oNone,Commands);
Core.Database.AddCommand(iCount, DB.TableP, useForFields, DB.IDs.Active,poNone,oNone,Commands);
Core.Database.AddCommand(iCount, DB.TableP, useForFields, DB.IDs.Alias,poNone,oNone,Commands);
Core.Database.AddCommand(iCount, DB.TableP, useForFields, DB.IDs.Holder,poNone,oNone,Commands);
