Core.Database.AddCommand(iCount, DB.TableP, useForFields, DB.IDs.ID, poNone, oNone, Commands);
Core.Database.AddCommand(iCount, DB.TableP, useForFields, DB.IDs.OwnerID, poNone, oNone, Commands);
Core.Database.AddCommand(iCount, DB.TableP, useForFields, DB.IDs.AvatarID, poNone, oNone, Commands);

Core.Database.AddCommand(iCount, DB.TableP, useForFields, DB.IDs.Created, poNone, oNone, Commands);
Core.Database.AddCommand(iCount, DB.TableP, useForFields, DB.IDs.Modified, poNone, oNone, Commands);
Core.Database.AddCommand(iCount, DB.TableP, useForFields, DB.IDs.MemberCount, poNone, oNone, Commands);

Core.Database.AddCommand(iCount, DB.TableP, useForFields, DB.IDs.DocumentsID, poNone, oNone, Commands);
Core.Database.AddCommand(iCount, DB.TableP, useForFields, DB.IDs.TrashID, poNone, oNone, Commands);
Core.Database.AddCommand(iCount, DB.TableP, useForFields, DB.IDs.MusicID, poNone, oNone, Commands);
Core.Database.AddCommand(iCount, DB.TableP, useForFields, DB.IDs.PicturesID, poNone, oNone, Commands);
Core.Database.AddCommand(iCount, DB.TableP, useForFields, DB.IDs.VideosID, poNone, oNone, Commands);

Core.Database.AddCommand(iCount, DB.TableP, useForFields, DB.IDs.Privacy, poNone, oNone, Commands);
Core.Database.AddCommand(iCount, DB.TableP, useForFields, DB.IDs.Tag, poNone, oNone, Commands);
Core.Database.AddCommand(iCount, DB.TableP, useForFields, DB.IDs.Title, poNone, oNone, Commands);
Core.Database.AddCommand(iCount, DB.TableP, useForFields, DB.IDs.Description, poNone, oNone, Commands);

