Core.Database.AddCommand(iCount,TableP,useForFields,IDs.ID,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.Date,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.Key,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.DerKey,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.Request,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.Level,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.Cert1,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.Cert2,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.Cert3,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.Cert4,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.DerCert1,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.DerCert2,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.DerCert3,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.DerCert4,poNone,oNone,Commands);

