Core.Database.AddCommand(iCount, DB.TableP, useForFields, DB.IDs.ID, poNone, oNone, Commands);

Core.Database.AddCommand(iCount, DB.TableP, useForFields, DB.IDs.ProviderID, poNone, oNone, Commands);
Core.Database.AddCommand(iCount, DB.TableP, useForFields, DB.IDs.NetworkID, poNone, oNone, Commands);
Core.Database.AddCommand(iCount, DB.TableP, useForFields, DB.IDs.GroupID, poNone, oNone, Commands);
Core.Database.AddCommand(iCount, DB.TableP, useForFields, DB.IDs.SessionID, poNone, oNone, Commands);
Core.Database.AddCommand(iCount, DB.TableP, useForFields, DB.IDs.QueryID, poNone, oNone, Commands);
Core.Database.AddCommand(iCount, DB.TableP, useForFields, DB.IDs.UserID, poNone, oNone, Commands);

Core.Database.AddCommand(iCount, DB.TableP, useForFields, DB.IDs.Created, poNone, oNone, Commands);
Core.Database.AddCommand(iCount, DB.TableP, useForFields, DB.IDs.Modified, poNone, oNone, Commands);
Core.Database.AddCommand(iCount, DB.TableP, useForFields, DB.IDs.Expires, poNone, oNone, Commands);
Core.Database.AddCommand(iCount, DB.TableP, useForFields, DB.IDs.Executed, poNone, oNone, Commands);


