Core.Database.AddCommand(iCount,TableP,useForInsert,IDs.DomainID,poNone,oNone,DomainID,Commands);
Core.Database.AddCommand(iCount,TableP,useForInsert,IDs.UserID,poNone,oNone,UserID,Commands);
Core.Database.AddCommand(iCount,TableP,useForInsert,IDs.FolderID,poNone,oNone,Item.FolderID,Commands);
Core.Database.AddCommand(iCount,TableP,useForInsert,IDs.Size,poNone,oNone,Item.Size,Commands);
Core.Database.AddCommand(iCount,TableP,useForInsert,IDs.Digest,poNone,oNone,Item.Digest,Commands);
Core.Database.AddCommand(iCount,TableP,useForInsert,IDs.Kind,poNone,oNone,Item.Kind,Commands);
Core.Database.AddCommand(iCount,TableP,useForInsert,IDs.Flags,poNone,oNone,Item.Flags,Commands);
Core.Database.AddCommand(iCount,TableP,useForInsert,IDs.Created,poNone,oNone,Item.Created,Commands);
Core.Database.AddCommand(iCount,TableP,useForInsert,IDs.Modified,poNone,oNone,Item.Modified,Commands);
Core.Database.AddCommand(iCount,TableP,useForInsert,IDs.Allocated,poNone,oNone,Item.Allocated,Commands);
Core.Database.AddCommand(iCount,TableP,useForInsert,IDs.Name,poNone,oNone,Item.Name,Commands);
Core.Database.AddCommand(iCount,TableP,useForInsert,IDs.Summary,poNone,oNone,Item.Summary,Commands);


