Core.Database.AddCommand(iCount,DB.TableP,useForInsert,DB.IDs.DomainID,poNone,oNone,DomainID,Commands);
Core.Database.AddCommand(iCount,DB.TableP,useForInsert,DB.IDs.OwnerID,poNone,oNone,OwnerID,Commands);
Core.Database.AddCommand(iCount,DB.TableP,useForInsert,DB.IDs.NetworkID,poNone,oNone,Item.NetworkID,Commands);
Core.Database.AddCommand(iCount,DB.TableP,useForInsert,DB.IDs.FolderID,poNone,oNone,Item.FolderID,Commands);
Core.Database.AddCommand(iCount,DB.TableP,useForInsert,DB.IDs.Size,poNone,oNone,Item.Size,Commands);
Core.Database.AddCommand(iCount,DB.TableP,useForInsert,DB.IDs.Digest,poNone,oNone,Item.Digest,Commands);
Core.Database.AddCommand(iCount,DB.TableP,useForInsert,DB.IDs.Kind,poNone,oNone,Item.Kind,Commands);
Core.Database.AddCommand(iCount,DB.TableP,useForInsert,DB.IDs.Created,poNone,oNone,Item.Created,Commands);
Core.Database.AddCommand(iCount,DB.TableP,useForInsert,DB.IDs.Modified,poNone,oNone,Item.Modified,Commands);
Core.Database.AddCommand(iCount,DB.TableP,useForInsert,DB.IDs.Allocated,poNone,oNone,Item.Allocated,Commands);
Core.Database.AddCommand(iCount,DB.TableP,useForInsert,DB.IDs.Name,poNone,oNone,Item.Name,Commands);
Core.Database.AddCommand(iCount,DB.TableP,useForInsert,DB.IDs.Summary,poNone,oNone,Item.Summary,Commands);

