Core.Database.AddCommand(iCount,TableP,useForFields,IDS.ID,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDS.UserName,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDS.Password,poNone,oNone,Commands);

Core.Database.AddCommand(iCount,TableP,useForFields,IDS.FirstName,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDS.LastName,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDS.Telephone,poNone,oNone,Commands);

Core.Database.AddCommand(iCount,TableP,useForFields,IDS.Auth,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDS.ForwardAddress,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDS.LastAccessed,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDS.LastQuotaEnforce,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDS.LastMessage,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDS.LastIP,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDS.Quota,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDS.Consumption,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDS.Throttle,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDS.Trash,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDS.Inbox,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDS.Spambox,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDS.Sentbox,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDS.Archivebox,poNone,oNone,Commands);



Core.Database.AddCommand(iCount,TableP,useForFields,IDS.Trashbox,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDS.Contact,poNone,oNone,Commands);


Core.Database.AddCommand(iCount,TableP,useForFields,IDS.Devices,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDS.Forwarding,poNone,oNone,Commands);

Core.Database.AddCommand(iCount,TableP,useForFields,IDS.Enabled,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDS.LockoutCount,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDS.ACLCoreObjects,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDS.ACLCoreCommands,poNone,oNone,Commands);



