Core.Database.AddCommand(iCount, DB.TableP, useForFields, DB.IDs.ID, poNone, oNone, Commands);
Core.Database.AddCommand(iCount, DB.TableP, useForFields, DB.IDs.NetworkID, poNone, oNone, Commands);
Core.Database.AddCommand(iCount, DB.TableP, useForFields, DB.IDs.UserID, poNone, oNone, Commands);
Core.Database.AddCommand(iCount, DB.TableP, useForFields, DB.IDs.TargetID, poNone, oNone, Commands);
Core.Database.AddCommand(iCount, DB.TableP, useForFields, DB.IDs.Kind, poNone, oNone, Commands);
Core.Database.AddCommand(iCount, DB.TableP, useForFields, DB.IDs.Posted, poNone, oNone, Commands);
