itmP^.ID:=Fields.FieldByName(Resources.DB.Keys.ID).AsLargeInt;
itmP^.ManifestID:=Fields.FieldByName(Resources.DB.Keys.ManifestID).AsLargeInt;
itmP^.SyncID:=Fields.FieldByName(Resources.DB.Keys.SyncID).AsLargeInt;
itmP^.Flags:=Fields.FieldByName(Resources.DB.Keys.Flags).AsInteger;
itmP^.Name:=Fields.FieldByName(Resources.DB.Keys.Name).AsString;
itmP^.Description:=Fields.FieldByName(Resources.DB.Keys.Description).AsString;

