Core.Database.AddCommand(iCount, DB.TableP, useForFields, DB.IDs.ID, poNone, oNone, Commands);
Core.Database.AddCommand(iCount, DB.TableP, useForFields, DB.IDs.NetworkID, poNone, oNone, Commands);
Core.Database.AddCommand(iCount, DB.TableP, useForFields, DB.IDs.OwnerID, poNone, oNone, Commands);
Core.Database.AddCommand(iCount, DB.TableP, useForFields, DB.IDs.Created, poNone, oNone, Commands);
Core.Database.AddCommand(iCount, DB.TableP, useForFields, DB.IDs.Accepted, poNone, oNone, Commands);
