Core.Database.AddCommand(iCount,TableP,useForFields,IDs.ID,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.Founded,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.Joined,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.Modified,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.Size,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.Auth,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.Name,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.Email,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.Website,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.Phone,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.Street1,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.Street2,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.City,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.Province,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.Postal,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.Country,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.Status,poNone,oNone,Commands);

