Core.Database.AddCommand(iCount,DB.TableP,useForFields,DB.IDs.ID,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,DB.TableP,useForFields,DB.IDs.UseID,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,DB.TableP,useForFields,DB.IDs.NodeID,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,DB.TableP,useForFields,DB.IDs.Kind,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,DB.TableP,useForFields,DB.IDs.Enabled,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,DB.TableP,useForFields,DB.IDs.Live,poNone,oNone,Commands);
