Core.Database.AddCommand(iCount, DB.TableP, useForValues, DB.IDs.Title, poNone, oNone, Item.Title, Commands);
Core.Database.AddCommand(iCount, DB.TableP, useForValues, DB.IDs.Description, poNone, oNone, Item.Description, Commands);
Core.Database.AddCommand(iCount, DB.TableP, useForValues, DB.IDs.Kind, poNone, oNone, Item.Kind, Commands);
Core.Database.AddCommand(iCount, DB.TableP, useForValues, DB.IDs.Price, poNone, oNone, Item.Price, Commands);
Core.Database.AddCommand(iCount, DB.TableP, useForValues, DB.IDs.Taxable, poNone, oNone, Item.Taxable, Commands);
Core.Database.AddCommand(iCount, DB.TableP, useForValues, DB.IDs.Available, poNone, oNone, Item.Available, Commands);
Core.Database.AddCommand(iCount, DB.TableP, useForValues, DB.IDs.Inventory, poNone, oNone, Item.Inventory, Commands);
Core.Database.AddCommand(iCount, DB.TableP, useForValues, DB.IDs.Backorder, poNone, oNone, Item.Backorder, Commands);
Core.Database.AddCommand(iCount, DB.TableP, useForValues, DB.IDs.Enabled, poNone, oNone, Item.Enabled, Commands);

