Core.Database.AddCommand(iCount, DB.TableP,useForFields,DB.IDs.CollageID,poNone,oNone,Commands);
Core.Database.AddCommand(iCount, DB.TableP,useForFields,DB.IDs.OwnerID,poNone,oNone,Commands);
Core.Database.AddCommand(iCount, DB.TableP,useForFields,DB.IDs.FolderID,poNone,oNone,Commands);
Core.Database.AddCommand(iCount, DB.TableP,useForFields,DB.IDs.FileID,poNone,oNone,Commands);
Core.Database.AddCommand(iCount, DB.TableP,useForFields,DB.IDs.NetworkID,poNone,oNone,Commands);
Core.Database.AddCommand(iCount, DB.TableP,useForFields,DB.IDs.Element,poNone,oNone,Commands);
Core.Database.AddCommand(iCount, DB.TableP,useForFields,DB.IDs.SubItem,poNone,oNone,Commands);
Core.Database.AddCommand(iCount, DB.TableP,useForFields,DB.IDs.MoveX,poNone,oNone,Commands);
Core.Database.AddCommand(iCount, DB.TableP,useForFields,DB.IDs.MoveY,poNone,oNone,Commands);
Core.Database.AddCommand(iCount, DB.TableP,useForFields,DB.IDs.ScaleX,poNone,oNone,Commands);
Core.Database.AddCommand(iCount, DB.TableP,useForFields,DB.IDs.ScaleY,poNone,oNone,Commands);
Core.Database.AddCommand(iCount, DB.TableP,useForFields,DB.IDs.Rotate,poNone,oNone,Commands);

