Core.Database.AddCommand(iCount,TableP,useForFields,IDs.ID,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.DomainID,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.Kind,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.ClusterID,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.ResourceID,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.NodeID,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.Port,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.State,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.Scale,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.Enabled,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.Ping,poNone,oNone,Commands);

