Core.Database.AddCommand(iCount,DB.TableP,useForFields,DB.IDs.ID,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,DB.TableP,useForFields,DB.IDs.DomainID,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,DB.TableP,useForFields,DB.IDs.NetworkID,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,DB.TableP,useForFields,DB.IDs.OwnerID,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,DB.TableP,useForFields,DB.IDs.FolderID,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,DB.TableP,useForFields,DB.IDs.Kind,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,DB.TableP,useForFields,DB.IDs.Size,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,DB.TableP,useForFields,DB.IDs.Created,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,DB.TableP,useForFields,DB.IDs.Modified,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,DB.TableP,useForFields,DB.IDs.Allocated,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,DB.TableP,useForFields,DB.IDs.Digest,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,DB.TableP,useForFields,DB.IDs.Name,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,DB.TableP,useForFields,DB.IDs.Summary,poNone,oNone,Commands);

