Core.Database.AddCommand(iCount, TableP,useForFields,IDs.ID,poNone,oNone,Commands);
Core.Database.AddCommand(iCount, TableP,useForFields,IDs.Created,poNone,oNone,Commands);
Core.Database.AddCommand(iCount, TableP,useForFields,IDs.Modified,poNone,oNone,Commands);
Core.Database.AddCommand(iCount, TableP,useForFields,IDs.Title,poNone,oNone,Commands);
Core.Database.AddCommand(iCount, TableP,useForFields,IDs.Data,poNone,oNone,Commands);
