Core.Database.AddCommand(iCount,TableP,useForFields,IDS.ID,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDS.Value,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDS.Kind,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDS.Enabled,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDS.Expires,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDS.Counter,poNone,oNone,Commands);

