Core.Database.AddCommand(iCount,DB.TableP,useForInsert,DB.IDs.DomainID,poNone,oNone,DomainID,Commands);
Core.Database.AddCommand(iCount,DB.TableP,useForInsert,DB.IDs.UserID,poNone,oNone,UserID,Commands);
Core.Database.AddCommand(iCount,DB.TableP,useForInsert,DB.IDs.ResourceID,poNone,oNone,ResourceID,Commands);
Core.Database.AddCommand(iCount,DB.TableP,useForInsert,DB.IDs.NodeID,poNone,oNone,Item.NodeID,Commands);
Core.Database.AddCommand(iCount,DB.TableP,useForInsert,DB.IDs.Limit,poNone,oNone,Limit,Commands);
Core.Database.AddCommand(iCount,DB.TableP,useForInsert,DB.IDs.ServerBufferSend,poNone,oNone,Item.ServerBuffer.Send,Commands);
Core.Database.AddCommand(iCount,DB.TableP,useForInsert,DB.IDs.ServerBufferRecv,poNone,oNone,Item.ServerBuffer.Recv,Commands);
Core.Database.AddCommand(iCount,DB.TableP,useForInsert,DB.IDs.ClientBufferSend,poNone,oNone,Item.ClientBuffer.Send,Commands);
Core.Database.AddCommand(iCount,DB.TableP,useForInsert,DB.IDs.ClientBufferRecv,poNone,oNone,Item.ClientBuffer.Recv,Commands);

