Core.Database.AddCommand(iCount,TableP,@Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.ID,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.CertID,poNone,oNone,Commands);

Core.Database.AddCommand(iCount,TableP,useForFields,IDs.Name,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.FriendlyName,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.Root,poNone,oNone,Commands);

Core.Database.AddCommand(iCount,TableP,useForFields,IDs.DefaultOptionCatchAll,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.DefaultOptionFiltering,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.DefaultOptionQuota,poNone,oNone,Commands);
