Core.Database.AddCommand(iCount, TableP, useForFields, IDs.ID,poNone,oNone,Commands);
Core.Database.AddCommand(iCount, TableP, useForFields, IDs.Title,poNone,oNone,Commands);
Core.Database.AddCommand(iCount, TableP, useForFields, IDs.Description,poNone,oNone,Commands);
Core.Database.AddCommand(iCount, TableP, useForFields, IDs.Kind,poNone,oNone,Commands);
Core.Database.AddCommand(iCount, TableP, useForFields, IDs.Price,poNone,oNone,Commands);
Core.Database.AddCommand(iCount, TableP, useForFields, IDs.Taxable,poNone,oNone,Commands);
Core.Database.AddCommand(iCount, TableP, useForFields, IDs.Available,poNone,oNone,Commands);
Core.Database.AddCommand(iCount, TableP, useForFields, IDs.Inventory,poNone,oNone,Commands);
Core.Database.AddCommand(iCount, TableP, useForFields, IDs.Backorder,poNone,oNone,Commands);
Core.Database.AddCommand(iCount, TableP, useForFields, IDs.Enabled,poNone,oNone,Commands);


