Core.Database.AddCommand(iCount,TableP,useForFields,IDs.ID,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.FolderID,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.UserID,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.DomainID,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.Kind,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.Flags,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.Size,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.Created,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.Modified,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.Allocated,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.Digest,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.Name,poNone,oNone,Commands);

