Core.Database.AddCommand(iCount,DB.TableP,useForInsert,DB.IDs.DomainID,poNone,oNone,DomainID,Commands);
Core.Database.AddCommand(iCount,DB.TableP,useForInsert,DB.IDs.UserID,poNone,oNone,UserID,Commands);
Core.Database.AddCommand(iCount,DB.TableP,useForInsert,DB.IDs.ResourceID,poNone,oNone,ResourceID,Commands);
Core.Database.AddCommand(iCount,DB.TableP,useForInsert,DB.IDs.NetworkID,poNone,oNone,NetworkID,Commands);
Core.Database.AddCommand(iCount,DB.TableP,useForInsert,DB.IDs.Modified,poNone,oNone,Core.Timer.dtUT,Commands);
