Core.Database.AddCommand(iCount,TableP,@Commands);
// Set Primary ID
Core.Database.AddCommand(iCount,TableP,useForInsert,IDs.InsertID,poNone,oNone,iInsertID,Commands);
Core.Database.AddCommand(iCount,TableP,useForCriteria,IDs.InsertID,poNone,oEqual,iInsertID,Commands);
Core.Database.AddCommand(iCount,TableP,useForPrimaryID,IDs.ID,poNone,oNone,Entry.ID,Commands);
Core.Database.AddCommand(iCount,TableP,useForResetInsertID,IDs.InsertID,poNone,oNone,iReset,Commands);


Core.Database.AddCommand(iCount,TableP,useForInsert,IDs.DomainID,poNone,oNone,Entry.DomainID,Commands);
Core.Database.AddCommand(iCount,TableP,useForInsert,IDs.UserID,poNone,oNone,Entry.UserID,Commands);
Core.Database.AddCommand(iCount,TableP,useForInsert,IDs.Modified,poNone,oNone,Entry.Modified,Commands);
Core.Database.AddCommand(iCount,TableP,useForInsert,IDs.Subscription,poNone,oNone,Entry.Subscription,Commands);
Core.Database.AddCommand(iCount,TableP,useForInsert,IDs.ResourceID,poNone,oNone,Entry.ResourceID,Commands);
Core.Database.AddCommand(iCount,TableP,useForInsert,IDs.AccountID,poNone,oNone,Entry.AccountID,Commands);
Core.Database.AddCommand(iCount,TableP,useForInsert,IDs.AvatarID,poNone,oNone,Entry.AvatarID,Commands);
Core.Database.AddCommand(iCount,TableP,useForInsert,IDs.URL,poNone,oNone,Entry.URL,Commands);
Core.Database.AddCommand(iCount,TableP,useForInsert,IDs.Email1,poNone,oNone,Entry.Email1,Commands);
Core.Database.AddCommand(iCount,TableP,useForInsert,IDs.Email2,poNone,oNone,Entry.Email2,Commands);
Core.Database.AddCommand(iCount,TableP,useForInsert,IDs.Email3,poNone,oNone,Entry.Email3,Commands);
Core.Database.AddCommand(iCount,TableP,useForInsert,IDs.Emails,poNone,oNone,Entry.Emails,Commands);
Core.Database.AddCommand(iCount,TableP,useForInsert,IDs.Text1,poNone,oNone,Entry.Text1,Commands);
Core.Database.AddCommand(iCount,TableP,useForInsert,IDs.Text2,poNone,oNone,Entry.Text2,Commands);
Core.Database.AddCommand(iCount,TableP,useForInsert,IDs.Text3,poNone,oNone,Entry.Text3,Commands);
Core.Database.AddCommand(iCount,TableP,useForInsert,IDs.Texts,poNone,oNone,Entry.Texts,Commands);

Core.Database.AddCommand(iCount,TableP,useForInsert,IDs.Phone1,poNone,oNone,Entry.Phone1,Commands);
Core.Database.AddCommand(iCount,TableP,useForInsert,IDs.Phone2,poNone,oNone,Entry.Phone2,Commands);
Core.Database.AddCommand(iCount,TableP,useForInsert,IDs.Phone3,poNone,oNone,Entry.Phone3,Commands);
Core.Database.AddCommand(iCount,TableP,useForInsert,IDs.Phones,poNone,oNone,Entry.Phones,Commands);

Core.Database.AddCommand(iCount,TableP,useForInsert,IDs.Folder,poNone,oNone,Entry.Folder,Commands);
Core.Database.AddCommand(iCount,TableP,useForInsert,IDs.NickName,poNone,oNone,Entry.NickName,Commands);
Core.Database.AddCommand(iCount,TableP,useForInsert,IDs.FirstName,poNone,oNone,Entry.FirstName,Commands);
Core.Database.AddCommand(iCount,TableP,useForInsert,IDs.MiddleName,poNone,oNone,Entry.MiddleName,Commands);
Core.Database.AddCommand(iCount,TableP,useForInsert,IDs.LastName,poNone,oNone,Entry.LastName,Commands);
Core.Database.AddCommand(iCount,TableP,useForInsert,IDs.Address1,poNone,oNone,Entry.Address1,Commands);
Core.Database.AddCommand(iCount,TableP,useForInsert,IDs.Address2,poNone,oNone,Entry.Address2,Commands);
Core.Database.AddCommand(iCount,TableP,useForInsert,IDs.City,poNone,oNone,Entry.City,Commands);
Core.Database.AddCommand(iCount,TableP,useForInsert,IDs.State,poNone,oNone,Entry.State,Commands);
Core.Database.AddCommand(iCount,TableP,useForInsert,IDs.Post,poNone,oNone,Entry.Post,Commands);
Core.Database.AddCommand(iCount,TableP,useForInsert,IDs.Country,poNone,oNone,Entry.Country,Commands);
Core.Database.AddCommand(iCount,TableP,useForInsert,IDs.Field1,poNone,oNone,Entry.Field1,Commands);
Core.Database.AddCommand(iCount,TableP,useForInsert,IDs.Field2,poNone,oNone,Entry.Field2,Commands);
Core.Database.AddCommand(iCount,TableP,useForInsert,IDs.Field3,poNone,oNone,Entry.Field3,Commands);
Core.Database.AddCommand(iCount,TableP,useForInsert,IDs.Field4,poNone,oNone,Entry.Field4,Commands);
Core.Database.AddCommand(iCount,TableP,useForInsert,IDs.Field5,poNone,oNone,Entry.Field5,Commands);
Core.Database.AddCommand(iCount,TableP,useForInsert,IDs.Fields,poNone,oNone,Entry.Fields,Commands);

