Core.Database.AddCommand(iCount,TableP,useForFields,IDs.ID,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.Size,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.Name,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.Imported,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.Attributes,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.ContentType,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.HasKeywords,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.Cache,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.CacheTTL,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.Digest,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.Deflate,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.Created,poNone,oNone,Commands);
Core.Database.AddCommand(iCount,TableP,useForFields,IDs.Modified,poNone,oNone,Commands);

