ProviderP^.Port:=Fields.FieldByName(Items.DB.Keys.ID).AsInteger;
ProviderP^.Scale:=Fields.FieldByName(Items.DB.Keys.Scale).AsInteger;
ProviderP^.MaxResults:=Fields.FieldByName(Items.DB.Keys.MaxResults).AsInteger;
ProviderP^.Caption:=Fields.FieldByName(Items.DB.Keys.Caption).AsString;
ProviderP^.Domain:=Fields.FieldByName(Items.DB.Keys.Domain).AsString;
ProviderP^.qsWeb:=Fields.FieldByName(Items.DB.Keys.qsWeb).AsString;
ProviderP^.qsNews:=Fields.FieldByName(Items.DB.Keys.qsNews).AsString;
ProviderP^.qsImage:=Fields.FieldByName(Items.DB.Keys.qsImage).AsString;
ProviderP^.qsVideo:=Fields.FieldByName(Items.DB.Keys.qsVideo).AsString;
ProviderP^.lpWeb:=Fields.FieldByName(Items.DB.Keys.lpWeb).AsString;
ProviderP^.lpNews:=Fields.FieldByName(Items.DB.Keys.lpNews).AsString;
ProviderP^.lpImage:=Fields.FieldByName(Items.DB.Keys.lpImage).AsString;
ProviderP^.lpVideo:=Fields.FieldByName(Items.DB.Keys.lpVideo).AsString;

