Core.Database.AddCommand(iCount, TableP,useForFields,IDs.ID,poNone,oNone,Commands);
Core.Database.AddCommand(iCount, TableP,useForFields,IDs.ProjectID,poNone,oNone,Commands);
Core.Database.AddCommand(iCount, TableP,useForFields,IDs.GroupID,poNone,oNone,Commands);
Core.Database.AddCommand(iCount, TableP,useForFields,IDs.Created,poNone,oNone,Commands);
Core.Database.AddCommand(iCount, TableP,useForFields,IDs.Modified,poNone,oNone,Commands);
Core.Database.AddCommand(iCount, TableP,useForFields,IDs.Due,poNone,oNone,Commands);
Core.Database.AddCommand(iCount, TableP,useForFields,IDs.Team,poNone,oNone,Commands);
Core.Database.AddCommand(iCount, TableP,useForFields,IDs.Admins,poNone,oNone,Commands);
Core.Database.AddCommand(iCount, TableP,useForFields,IDs.Files,poNone,oNone,Commands);
Core.Database.AddCommand(iCount, TableP,useForFields,IDs.Comments,poNone,oNone,Commands);
Core.Database.AddCommand(iCount, TableP,useForFields,IDs.Creator,poNone,oNone,Commands);
Core.Database.AddCommand(iCount, TableP,useForFields,IDs.Frequency,poNone,oNone,Commands);
Core.Database.AddCommand(iCount, TableP,useForFields,IDs.Status,poNone,oNone,Commands);
Core.Database.AddCommand(iCount, TableP,useForFields,IDs.Caveats,poNone,oNone,Commands);
Core.Database.AddCommand(iCount, TableP,useForFields,IDs.Skills,poNone,oNone,Commands);
Core.Database.AddCommand(iCount, TableP,useForFields,IDs.Title,poNone,oNone,Commands);

