Core.Database.AddCommand(iCount, TableP, useForInsert, IDs.NodeID, poNone, oNone, NodeID, Commands);
Core.Database.AddCommand(iCount, TableP, useForInsert, IDs.DiskID, poNone, oNone, Disk.ID, Commands);
Core.Database.AddCommand(iCount, TableP, useForInsert, IDs.Kind, poNone, oNone, aKind, Commands);
Core.Database.AddCommand(iCount, TableP, useForInsert, IDs.TTL, poNone, oNone, TTL, Commands);
Core.Database.AddCommand(iCount, TableP, useForInsert, IDs.Locked, poNone, oNone, Defaults.Locked, Commands);
Core.Database.AddCommand(iCount, TableP, useForInsert, IDs.Trys, poNone, oNone, Defaults.Trys, Commands);
Core.Database.AddCommand(iCount, TableP, useForInsert, IDs.Meta, poNone, oNone, Meta, Commands);

